-d C:\Users\jordi\OneDrive\Documents\Projects\FPGA\vdp20k\impl\gwsynthesis\hdmi.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\jordi\OneDrive\Documents\Projects\FPGA\vdp20k\src\hdmi.cst
-cfg C:\Users\jordi\OneDrive\Documents\Projects\FPGA\vdp20k\impl\pnr\device.cfg
-sdc C:\Users\jordi\OneDrive\Documents\Projects\FPGA\vdp20k\src\nano_20k_video.sdc
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
